---
name: "Meilisearch"
guid: "974395db-b31d-46a2-bc86-ef9aa5ac04dd"
version: "1.7.0.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
overview: "Meilisearch Plugin"
description: >
  This is a plugin that try to use Meilisearch to speedup the search of jellyfin.
  Inspired by Jellysearch
category: "General"
owner: "a.sac."
artifacts:
  - "Jellyfin.Plugin.Meilisearch.dll"
  - "Jellyfin.Plugin.Meilisearch.pdb"
  - "Meilisearch.dll"
  - "Microsoft.IdentityModel.Abstractions.dll"
  - "Microsoft.IdentityModel.JsonWebTokens.dll"
  - "Microsoft.IdentityModel.Logging.dll"
  - "Microsoft.IdentityModel.Tokens.dll"
  - "System.IdentityModel.Tokens.Jwt.dll"
changelog: >
  changelog